Travis update (#8)
* reattach head

* Verify output file present

* Fix logic in if statement

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -12,6 +12,16 @@ before_install:
     - make
     - sudo make install
     - popd
+    - git checkout ${TRAVIS_BRANCH}
+    - git branch -u origin/${TRAVIS_BRANCH}
+    - git config branch.${TRAVIS_BRANCH}.remote origin
+    - git config branch.${TRAVIS_BRANCH}.merge refs/heads/${TRAVIS_BRANCH}
 
 script:
-    - ./remoll-run.sh runexample.mac
+    - |
+      ./remoll-run.sh runexample.mac
+      if [ ! -f rootfiles/remollout.root ]; then
+        printf >&2 "Remoll output file not found.\\n"
+        exit 1
+      fi
+
